backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown}, {label: Image, name: image, widget: image}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/about/our-team.md"
        label: "Our team"
        name: "our-team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "our-team"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Subtitle, name: subtitle, widget: string}]}
          - {
            label: Intro,
            name: intro, 
            widget: object, 
            fields: [
              {
                label: Blurbs, 
                name: blurbs, 
                widget: list, 
                fields: [
                  {label: Image, name: image, widget: image},{label: Header, name: header, widget: text},{label: Text, name: text, widget: text},{label: Description, name: description, widget: markdown}
                ]
              },
              {
                label: Advisory, 
                name: advisory, 
                widget: list, 
                fields: [
                  {label: Image, name: image, widget: image},{label: Header, name: header, widget: text},{label: Text, name: text, widget: text},{label: Description, name: description, widget: markdown}
                ]
              }              
            ]
          }
      - file: "src/pages/about/understanding-cannabis.md"
        label: "Understanding Cannabis"
        name: "understanding-cannabis"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "understanding-cannabis"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Subtitle, name: subtitle, widget: string}]}
      - file: "src/pages/operations/docs-place-international.md"
        label: "Docs Place International"
        name: "docs-place-international"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "docs-place-international"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown}, {label: List, name: list, widget: markdown}]}
      - file: "src/pages/operations/medically-supervised-trials.md"
        label: "Medically Supervised Trials"
        name: "medically-supervised-trials"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "medically-supervised-trials"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown}]}
      - file: "src/pages/operations/artificial-intelligence.md"
        label: "Artificial Intelligence"
        name: "artificial-intelligence"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "artificial-intelligence"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown},{label: Image, name: image, widget: image},{label: Footnote, name: footnote, widget: string}]}
      - file: "src/pages/products/trademarked-products.md"
        label: "Trademarked Products"
        name: "trademarked-products"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "trademarked-products"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Main, name: main, widget: object, fields: [{label: Description, name: description, widget: markdown}]}
          - {label: Products, name: products, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/products/3d-printer.md"
        label: "3D Printer"
        name: "3d-printer"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "3d-printer"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: List, name: list, widget: markdown}]}
      - file: "src/pages/products/cultivation-processing-and-extraction.md"
        label: "Cultivation, processing & extraction"
        name: "cultivation-processing-and-extraction"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cultivation-processing-and-extraction"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string},{label: Description, name: description, widget: markdown},{label: Subtitle, name: subtitle, widget: string},{label: Subdescription, name: subdescription, widget: markdown},{label: Footernote, name: footernote, widget: markdown}, {label: List, name: list, widget: markdown}]}
      - file: "src/pages/regulation/apollon-licences.md"
        label: "Apollon Licences"
        name: "apollon-licences"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "apollon-licences"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown},{label: List, name: list, widget: markdown}]}
      - file: "src/pages/regulation/global-regulation.md"
        label: "Global Regulation"
        name: "global-regulation"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "global-regulation"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown}]}
      - file: "src/pages/regulation/jamaican-regulatory-environment.md"
        label: "Jamaican Regulatory Environment"
        name: "jamaican-regulatory-environment"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "jamaican-regulatory-environment"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown},{label: List, name: list, widget: markdown}]}
      - file: "src/pages/regulation/uk-regulation.md"
        label: "UK Regulation"
        name: "uk-regulation"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "uk-regulation"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown}]}                    
      - file: "src/pages/investor-relations/index.md"
        label: "Investor Relations"
        name: "investor-relations"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "investor-relations"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text}]}]}
          - {label: Pdf, name: pdf, widget: object, fields: [{label: Downloads, name: downloads, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Updated, name: updated, widget: string},{label: Text, name: text, widget: text},{label: Url, name: url, widget: file}]}]}
      - file: "src/pages/investor-relations/shareholder-information.md"
        label: "Shareholder Information"
        name: "shareholder-information"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shareholder-information"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown},{label: List, name: list, widget: markdown}]}
          - {label: Shareholders, name: shareholders, widget: object, fields: [{label: Item, name: item, widget: list, fields: [{label: Shareholder, name: shareholder, widget: text},{label: Number of Shares, name: numberofshares, widget: text},{label: Percentage of Shares, name: percentageofshares, widget: text}]}]}
      - file: "src/pages/investor-relations/presentations-and-reports.md"
        label: "Presentations & Reports"
        name: "presentations-and-reports"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "presentations-and-reports"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Presentations, name: presentations, widget: object, fields: [{label: Downloads, name: downloads, widget: list, fields: [{label: Name, name: name, widget: text},{label: Text, name: text, widget: text},{label: Url, name: url, widget: file}]}]}
          - {label: Reports, name: reports, widget: object, fields: [{label: Downloads, name: downloads, widget: list, fields: [{label: Name, name: name, widget: text},{label: Text, name: text, widget: text},{label: Url, name: url, widget: file}]}]}
      - file: "src/pages/investor-relations/news-and-media.md"
        label: "News & Media"
        name: "news-and-media"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-and-media"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: News, name: news, widget: object, fields: [{label: Item, name: item, widget: list, fields: [{label: Date, name: date, widget: text},{label: Text, name: text, widget: text},{label: Url, name: url, widget: file}]}]}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: text},{label: Vimeo Id, name: vimeoid, widget: text},{label: Date, name: date, widget: text},{label: Vimeo Title, name: vimeotitle, widget: text}]}
          - {label: Video, name: video, widget: object, fields: [{label: Item, name: item, widget: list, fields: [{label: Vimeo Id, name: id, widget: number},{label: Image, name: image, widget: image},{label: Date, name: date, widget: text},{label: Title, name: title, widget: text}]}]}
      - file: "src/pages/investor-relations/regulatory-news.md"
        label: "Regulatory news"
        name: "regulatory-news"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "regulatory-news"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: News, name: news, widget: object, fields: [{label: Item, name: item, widget: list, fields: [{label: Date, name: date, widget: text},{label: Text, name: text, widget: text},{label: Url, name: url, widget: file}]}]}
      - file: "src/pages/investor-relations/aqse-rule-71.md"
        label: "AQSE Rule 71"
        name: "aqse-rule-71"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aqse-rule-71"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: markdown}]}
      - file: "src/pages/investor-relations/advisers.md"
        label: "Advisers"
        name: "advisers"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "advisers"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Advisers, name: advisers, widget: object, fields: [{label: Item, name: item, widget: list, fields: [{label: Name, name: header, widget: string},{label: First Line of Address, name: text, widget: string},{label: Address, name: description, widget: markdown}]}]}


          