backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/holding.md"
        label: "Holding Page"
        name: "holding"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "holding-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
          - {label: Products, name: products, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
          - {label: Products, name: products, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Image, name: image, widget: image}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
          - {label: Products, name: products, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/about/our-team.md"
        label: "Our team"
        name: "our team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Subtitle, name: subtitle, widget: string}]}
          - {
            label: Intro,
            name: intro, 
            widget: object, 
            fields: [
              {
                label: Blurbs, 
                name: blurbs, 
                widget: list, 
                fields: [
                  {label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text},{label: Description, name: description, widget: markdown}
                ]
              },
              {
                label: Advisory, 
                name: advisory, 
                widget: list, 
                fields: [
                  {label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text},{label: Description, name: description, widget: markdown}
                ]
              }              
            ]
          }
      - file: "src/pages/about/understanding-cannibis.md"
        label: "Understanding Cannibis"
        name: "understanding cannibis"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "understanding-cannibis"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
          - {label: Products, name: products, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/operations/docs-place-international.md"
        label: "Docs Place International"
        name: "docs place international"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "docs-place-international"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
      - file: "src/pages/operations/medically-supervised-trials.md"
        label: "Medically Supervised Trials"
        name: "medically supervised trials"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "medically-supervised-trials"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
      - file: "src/pages/operations/ai.md"
        label: "Artificial Intelligence"
        name: "artificial intelligence"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ai"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string} 
      - file: "src/pages/products/trademarked-products.md"
        label: "Trademarked Products"
        name: "Trademarked Products"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "trademarked-products"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}
          - {label: Featuretitle, name: featuretitle, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text},{label: Header, name: header, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}]}
          - {label: Carousel, name: carousel, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
          - {label: Products, name: products, widget: object, fields: [{label: Slides, name: slides, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: text}]}]}
      - file: "src/pages/products/3d-printer.md"
        label: "3D Printer"
        name: "3d printer"    
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "three-d"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: markdown}, {label: Subtitle, name: subtitle, widget: string}, {label: Subdescription, name: subdescription, widget: markdown}]}
          - {label: Heading, name: heading, widget: string}                            
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/partners/index.md"
        label: "Partners Page"
        name: "partners"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partner-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
